# Sprint 2

## Problem 1

In [13]:
import random
def scratch_train_test_split(X, y, train_size = 0.8,seed = 0):
    if type(X) != np.ndarray:
        X = np.array(X)
    if type(y) != np.ndarray:
        y = np.array(y)
    
    random.seed(seed)
    list_i = [i for i in range(X.shape[0])]
    random.shuffle(list_i)
    rnd_X = X[list_i]
    rnd_y = y[list_i]
    size = round(X.shape[0] * train_size)
    X_train, X_test = np.split(rnd_X, [size])
    y_train, y_test = np.split(rnd_y, [size])
    
    return X_train, X_test, y_train, y_test

In [14]:
#testing the funtion
import numpy as np
X= np.ones((4,4))
y =  np.ones(4)
train = X[:3]
test = X[3:]

In [15]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=5)

In [17]:
print('X_train:',X_train)
print('X_test:',X_test)
print('y_train:',y_train)
print('y_test:',y_test)

X_train: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
X_test: [[1. 1. 1. 1.]]
y_train: [1. 1. 1.]
y_test: [1.]


## Problem 2

In [20]:
from sklearn.datasets import load_iris
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
iris = load_iris()
X = iris.data[50:]
y = iris.target[50:]
y = np.where(y == 1, 0, 1)

In [22]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [23]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X = X, y = y, train_size=0.8,seed=0)

In [24]:
clf = SGDClassifier(loss="log")
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
0.95
0.9090909090909091
1.0
0.9523809523809523
[[ 9  1]
 [ 0 10]]


In [25]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
0.9
0.8333333333333334
1.0
0.9090909090909091
[[ 8  2]
 [ 0 10]]


/Users/diopmouhamed/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [26]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
0.9
0.8333333333333334
1.0
0.9090909090909091
[[ 8  2]
 [ 0 10]]


In [27]:
import numpy as np

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

In [28]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [29]:
clf = SGDClassifier(loss="log")
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
1.0
1.0
1.0
1.0
[[47  0]
 [ 0 53]]


In [30]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
1.0
1.0
1.0
1.0
[[47  0]
 [ 0 53]]


/Users/diopmouhamed/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [31]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
1.0
1.0
1.0
1.0
[[47  0]
 [ 0 53]]


In [32]:
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [34]:
clf = SGDClassifier(loss="log")
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
0.5
0.6666666666666666
0.4
0.5
[[2 1]
 [3 2]]


In [35]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
0.75
0.8
0.8
0.8000000000000002
[[2 1]
 [1 4]]


/Users/diopmouhamed/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [36]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("{}".format(clf.score(X_test, y_test)))
print("{}".format(precision_score(y_test,clf_pred)))
print("{}".format(recall_score(y_test,clf_pred)))
print("{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
0.875
1.0
0.8
0.888888888888889
[[3 0]
 [1 4]]


## Problem 3

In [39]:
import pandas as pd
df = pd.read_csv("train.csv")
X = df[["GrLivArea", "YearBuilt"]]
y = df["SalePrice"]

In [42]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [43]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model

In [44]:
clf = linear_model.SGDRegressor()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(clf)
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred)))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred)))
print("Root Mean Squared Error: {}".format(np.sqrt(mean_squared_error(y_test, y_pred))))
print("R squared (Coefficient of determination): {}".format(r2_score(y_test, y_pred)))

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)
Mean Absolute Error: 746680295157462.1
Mean Squared Error: 6.831962383816335e+29
Root Mean Squared Error: 826556857319345.9
R squared (Coefficient of determination): -1.2966673073395473e+20
